<?php
/**
 * Mohan_ProductQueueSave
 *
 * NOTE: Auto-generated by Magento DI; this stub is for IDE completion only.
 */

declare(strict_types=1);

namespace Mohan\ProductQueueSave\Model\ResourceModel\Queue\Log;

use Magento\Framework\ObjectManagerInterface;

/**
 * @codeCoverageIgnore
 */
class CollectionFactory
{
    public function __construct(
        private readonly ObjectManagerInterface $objectManager
    ) {}

    public function create(array $data = []): Collection
    {
        return $this->objectManager->create(Collection::class, $data);
    }
}
