<?php
/**
 * Mohan_ProductQueueSave
 *
 * NOTE: Auto-generated by Magento; this stub is provided for IDE assistance only.
 */

declare(strict_types=1);

namespace Mohan\ProductQueueSave\Model\Queue;

use Magento\Framework\ObjectManagerInterface;

/**
 * @codeCoverageIgnore
 */
class LogFactory
{
    public function __construct(
        private readonly ObjectManagerInterface $objectManager
    ) {}

    public function create(array $data = []): Log
    {
        return $this->objectManager->create(Log::class, $data);
    }
}
